### ISSUE TITLE
JSyntaxPane doesn't run in Java 5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aymanhs/jsyntaxpane#38]
```
When running RESTClient with JSyntaxPane 0.9.3 in Java 5, I am getting this
trace:

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError:
java.util.Properties.stringPropertyNames()Ljava/util/Set;
    at jsyntaxpane.DefaultSyntaxKit.initKit(DefaultSyntaxKit.java:185)
    at jsyntaxpane.DefaultSyntaxKit.<clinit>(DefaultSyntaxKit.java:64)
    at
org.wiztools.restclient.ui.JSyntaxPaneScriptEditor.<init>(JSyntaxPaneScriptEdito
r.java:16)
    at
org.wiztools.restclient.ui.ScriptEditorFactory.getXMLScriptEditor(ScriptEditorFa
ctory.java:19)

I think java.util.Properties has introduced stringPropertyNames() method in
version 6. We have to find corresponding method in Java and update the
JSyntaxPane code so that it is compatible with Java 5.
```

Original issue reported on code.google.com by `subwiz` on 15 Nov 2008 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
This is similar to issue 32.  But it there may be more than this method which is
available in 1.6 only.
```

Original comment by `ayman.al...@gmail.com` on 16 Nov 2008 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
I did a refactor to a java 5 compatible API, but as you said, there are other
dependencies--including javax.swing.GroupLayout--which is available only in 
Java 6.
So I have not committed my changes. To make RESTClient compatible with 
JSyntaxPane,
the minimum requirement will be raised from Java 5 to Java 6 since version 2.2 
of
RESTClient.

Closing this issue.
```

Original comment by `subwiz` on 16 Nov 2008 at 9:29
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Too bad it's java 6 only, that excludes a large part of the installed JREs.

There is a java 5 backport for GroupLayout btw. 

If there's no real dependency on java 6 that is absolutely necessary, you're 
just
being lazy and are keeping this project from becoming reaching its full 
potential. 

Do the right thing and make it available on Java 5 please.
```

Original comment by `yanic.in...@gmail.com` on 18 Nov 2008 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
It's not about being lazy.  The GroupLayout can be removed from the library as 
it is
used in a tester class, which can actually be removed altogether.  However 
there are
JDK 6 dependencies, using the CharSequence, the Segment class, and possibly 
others.  
Plus, the JDK 5 has already entered its End-Of-Life phase.
```

Original comment by `ayman.al...@gmail.com` on 18 Nov 2008 at 10:36
